# Generated by Django 3.2 on 2021-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
