# Generated by Django 3.2 on 2021-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='link',
            field=models.CharField(max_length=2055, null=True),
        ),
    ]
