# Generated by Django 3.2 on 2021-05-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
